#!/usr/bin/env bash

makedir -p ~/.xlcore/logs

if [ $1 == "run" ]; then exit; fi

# Working directory is actually the steam install location, so we need to find the path of this script
# tooldir="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
tooldir="$(realpath "$(dirname "$0")")"

# If aria2c isn't found, add our local copy to the $PATH
count=$(find /usr -type f -executable -name "aria2c" 2>/dev/null | wc -l)
if (( $count == 0 )); then
    PATH=$PATH:$tooldir/bin
fi

# Work around a Steam overlay bug.
export ldpreload="$LD_PRELOAD"
unset LD_PRELOAD

# Do some logging. Mostly for debug purposes.
echo "$(date +'%F %T.%3N %:z') [INF] [$0] Running Steam Compatibility Tool at $tooldir/xlcore-bin/XIVLauncher.Core $@" >> ~/.xlcore/logs/launcher.log
printenv > ~/.xlcore/logs/steamenv.log

echo $ldpreload >~/xivlauncher-sct_steamconsole.log

export OPENSSL_CONF="$tooldir/xlcore-bin/openssl_fix.cnf"
"$tooldir/xlcore-bin/XIVLauncher.Core" $@
